export default class Unit01 {
    static title = 'Introdução e Principais Dúvidas';
    static topics = [
        'Introdução e Principais Dúvidas',
        'Primeiros Passos',
        'FAQ',
        'Carreira e Tecnologia',
        'Quando inicia o apoio do time de carreira?',
        'Como o time de carreira vai me ajudar a partir da seção 10 do módulo de Back-end?',
        'Como mostrar sua experiência a partir dos aprendizados na Trybe?',
        'Como funciona o 1:1 de carreira?',
        'O que é networking?',
        'O que é pitch?',
        'Vagas para atuação em meio período são somente para contrato de estágio?',
        'Como me preparar para trabalhar fora do Brasil?',
        'Currículo',
        'Devo personalizar meu currículo para cada vaga que aplicar?',
        'Não tenho experiência profissional. O que devo colocar no meu currículo?',
        'Aplicações em vagas',
        'Devo me aplicar para uma vaga que não atendo todos os requisitos?',
        'Posso me aplicar para mais de uma vaga na mesma empresa?',
        'Devo continuar me aplicando em outras oportunidades mesmo tendo uma entrevista agendada em outro processo seletivo?',
        'Como saber se a vaga é realmente remota/home office?',
        'As empresas parceiras dão preferência para quem é da Trybe?',
        'Recebi uma negativa da empresa e ela abriu nova vaga. Posso me candidatar novamente?',
        'Entrevistas e etapas técnicas',
        'O que é avaliado numa entrevista comportamental ou de fit cultural?',
        'Como informar pretensão salarial?',
        'Devo perguntar o salário na primeira entrevista?',
        'Caso a empresa não tenha me passado um prazo para a realização do teste técnico, como devo agir?',
        'Caso eu não consiga entregar o teste técnico dentro do prazo previsto, posso propor uma nova data?',
        'Posso comentar numa entrevista que estou participando de outros processos?',
        'Durante uma entrevista, posso levar pontos pessoais da minha história ou devo focar no profissional?',
        'Me chamaram para entrevista de vaga que ainda não aprendi as tecnologias, o que fazer?',
        'Abordagem com empresas',
        'Não tive retorno sobre minha inscrição ou entrevista. Quando devo entrar em contato com a empresa?',
        'É uma boa prática abordar pessoas no LinkedIn? Como fazer isso da forma correta?',
        'Fui reprovado ou reprovada e não sei por que. Devo perguntar?',
        'Devo abordar pessoas recrutadoras ou pessoas técnicas?',
        'Modalidade de Contratação',
        'CLT ou PJ: saiba qual é a melhor forma de contratação para você',
        'CLT e PJ: quais as características de cada uma',
        'Principais benefícios, direitos e preocupações da CLT',
        'Principais benefícios, direitos e preocupações da PJ',
        'O que você deve saber antes de tomar uma decisão',
        'Aceitei uma proposta PJ, e agora?',
        'O que preciso saber ao me “tornar” PJ?',
        'Afinal, o que vale mais a pena? CLT ou PJ?',
    ];
}
